<%@ Page Title="" Language="C#" MasterPageFile="~/Models/Layout.Master" AutoEventWireup="true" CodeBehind="UploadImages.aspx.cs" Inherits="Front.Pages.UploadImages" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <title>Carregar base de Imagens</title>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="body" runat="server">
    <div class="container-fluid">
        <h1>Carregar Base de Imagens</h1>
        <p>Para treinar realizar a primeira verificação das faces dos novos alunos é necessário importar um arquivo .ZIP com as imagens dos alunos, onde o nome dos arquivos deve ser o código do respectivo aluno</p>
        <hr>
        <div class="form-group">
            <asp:Label runat="server" ID="Msg"></asp:Label>
            <br />
            <label for="exampleInputFile">Anexar arquivo</label>
            <asp:FileUpload runat="server" ID="FileFld" Width="500" placeholder="Nenhum arquivo selecionado" CssClass="form-control" accept=".zip"/>
        </div>
        <asp:Button runat="server" CssClass="btn btn-primary btn-block" Width="150" Text="Executar" ID="TryUpload" OnClick="TryUpload_Click"/>
        <br />
        <br />
        <div>
            <asp:GridView runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="false" AutoGenerateEditButton="false" AutoGenerateSelectButton="false" ID="ResultGrd">
                <Columns>
                    <asp:BoundField DataField="Status" HeaderText="Status"/>
                    <asp:BoundField DataField="Log" HeaderText="Mensagem"/>
                </Columns>
            </asp:GridView>
        </div>
    </div>
</asp:Content>
